### ISSUE TITLE
Wrong markup

### ISSUE THREAD

**Issue by weranda** [dlon/html2markdown#8] opened 2019-04-08 19:19 UTC
When I try to convert HTML, then I get the wrong output.

Example:
```
In [1]: a = '<blockquote><a href="url_address">text</a></blockquote>'
In [2]: html2markdown.convert(a)
Out[2]: ' [text](url_address'
```

But if I add whitespace before closing tag, then everything works fine except for a space at the beginning of a line:
```
In [1]: a = '<blockquote><a href="url_address">text</a> </blockquote>'
In [2]: html2markdown.convert(a)
Out[2]: ' [text](url_address)'
```

Maybe you know how to fix it?

**Comment by dlon** [comment] 2019-04-09 19:19
I can't reproduce it but it looks like there's a character missing on each side. What's your version of Python and bs4? To check the latter: `python -c "import bs4; print(bs4.__version__)"`

**Comment by weranda** [comment] 2019-04-11 09:40
> I can't reproduce it but it looks like there's a character missing on each side. What's your version of Python and bs4? To check the latter: `python -c "import bs4; print(bs4.__version__)"`

@dlon 
Python: 3.7
beautifulsoup4: 4.7.1

Update.
Very strange, but now works fine, I just restart the virtual environment.

**Comment by dlon** [comment] 2019-04-17 15:51
Alright. Closing this until it happens again. I wonder if it might be related to stdout and not the actual string

**Closed as completed by dlon** 2019-04-17 15:51 UTC
